### ISSUE TITLE
[Bug] Fail to save mmcv py files

### ISSUE THREAD

**Issue by LongGieGie** [XHwind/HM-ViT#6]
Traceback (most recent call last):
  File "/root/.cache/JetBrains/RemoteDev/dist/dc223052051f7_pycharm-professional-243.22562.68/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.cache/JetBrains/RemoteDev/dist/dc223052051f7_pycharm-professional-243.22562.68/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/autodl-tmp/HM-ViT/opencood/tools/train_camera.py", line 231, in <module>
    main()
  File "/root/autodl-tmp/HM-ViT/opencood/tools/train_camera.py", line 108, in main
    saved_path = train_utils.setup_train(hypes)
  File "/root/autodl-tmp/HM-ViT/opencood/tools/train_utils.py", line 105, in setup_train
    save_yaml(hypes, save_name)
  File "/root/autodl-tmp/HM-ViT/opencood/hypes_yaml/yaml_utils.py", line 341, in save_yaml
    cfg.dump(mmcv_file_path)
  File "/root/miniconda3/envs/hmvit/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dump'

Which happens when `mmcv<=1.4.5` due to mmcv deepcopy bug, and cfg is incorrectly copied as a ConfigDict object.

https://github.com/open-mmlab/mmcv/pull/1658#issue-1098641611
https://blog.csdn.net/qq_39967751/article/details/123074267

**Comment by LongGieGie** [comment]
Wrapping cfg as Config object works well

```python
def save_yaml(data, save_name):
    param = copy.deepcopy(data)
    if "mmcv_file_path_ptr" in data:
        fileDirname = "/".join(save_name.split("/")[:-1])
        for mmcv_file_path_ptr in param['mmcv_file_path_ptr']:
            mmcv_file_path_ptr = mmcv_file_path_ptr.split(".")

            mmcv_file_path = param
            for attr_name in mmcv_file_path_ptr:
                mmcv_file_path = mmcv_file_path[attr_name]
            mmcv_file_name = mmcv_file_path.split("/")[-1]
            assert ".py" in mmcv_file_name, "mmcv file must be .py file"
            mmcv_file_path = os.path.join(fileDirname, mmcv_file_name)

            update_content = param
            for attr_name in mmcv_file_path_ptr[:-1]:
                update_content = update_content[attr_name]
            cfg = update_content['cfg']
            # Wrap as Config object
            cfg = Config(cfg_dict=cfg, filename=data['model']['args']['camera']["BEVFormer"]['cfg'].filename)
            cfg.dump(mmcv_file_path)
            update_content['cfg'] = ""# will reload and parse it when loading yaml
```

**Comment by LongGieGie** [comment]
TypeError: FormatCode() got an unexpected keyword argument 'verify'

Which happens when `yapf` version is too high
`pip install yapf==0.40.1`
